#!/bin/sh

cp keystore keystore.orig
keytool -storepasswd -keystore keystore -new xchangecore.1549 -storepass changeit
keytool -genkey -alias core1 -keystore keystore -storepass xchangecore.1549 -validity 365 -keypass xchangecore.1549 -dname cn=core1,dc=xchangecore,dc=us

echo cd $CATALINA_HOME
keytool -genkey -keyalg RSA -keysize 2048 -alias tomcat -keystore keystore.jks -storepass xchangecore.1549 -keypass xchangecore.1549 -validity 365 -dname cn=core1,ou=xchangecore,o=xchangecore,l=xchangecore,st=xchangecore,c=US


