#!/bin/sh

echo Install the xChagneCore environment
echo There are couple tools needed to be installed if they have not installed yet, such as Java, rpl, unzip, curl, mysql-server
echo The way to install are:
echo 	- sudo apt-get install rpl
echo 	- sudo apt-get install unzip
echo 	- sudo apt-get install curl
echo 	- sudo apt-get install mysql-server

echo Install the OpenDJ ...
cd opendj && setup

echo Install the Tomcat ...
echo tomcat && setup

echo Install the OpenFire ...
cd openfire && setup
