#!/bin/sh
echo.
echo INSTALL:  Openfire
echo sudo dpkg -i openfire_3.7.1_all.deb

echo INFO: create tables for OpenFire
cp conf/openfire_mysql.sql.orig conf/openfire_mysql.sql
rpl "%ADMINPASS%" "xc.1549" conf/openfire_mysql.sql
mysql -u root -p < conf/openfire_mysql.sql
rm conf/openfire_mysql.sql

echo INFO: Generating self-signed keys for Openfire
echo cd %OPENFIRE_HOME%\resources\security
echo set SERVER_DNAME="cn=%FQDN%,dc=uicds,dc=us"
echo export DAYS_VALID=365

echo %KEYTOOLEXE% -storepasswd -keystore keystore -new %SYSADMINPASS% -storepass changeit
echo %KEYTOOLEXE% -genkey -alias %FQDN% -keystore keystore -storepass %SYSADMINPASS% -validity %DAYS_VALID% -keypass %SYSADMINPASS% -dname %SERVER_DNAME%

echo cd %INSTALL_HOME%
echo echo INFO: Generating self-signed keys for Tomcat 
echo %KEYTOOLEXE% -genkey -keyalg RSA -keysize 2048 -alias tomcat -keystore keystore.jks -storepass %SYSADMINPASS% -keypass %SYSADMINPASS% -validity %DAYS_VALID% -dname "CN=%FQDN%,ou=uicds,o=uicds,l=uicds,st=uicds,c=US"

