#!/bin/sh

echo INSTALL:  Openfire
sudo dpkg -i openfire_3.7.1_all.deb

echo INFO: create the database: dbopenfire and user: openfire
cp conf/create_mysql.sql.orig conf/create_mysql.sql
rpl "OPENFIRE_MYSQL_PASS%" "xc.1549" conf/create_mysql.sql
mysql -u root -p < conf/create_mysql.sql
rm conf/create_mysql.sql

echo INFO: create tables for OpenFire
cp conf/openfire_mysql.sql.orig conf/openfire_mysql.sql
rpl "%OPENFIRE_ADMIN_PASS%" "xc.1549" conf/openfire_mysql.sql
mysql -u root -p < conf/openfire_mysql.sql
rm conf/openfire_mysql.sql

echo INFO: Generating self-signed keys for Openfire
cp installKeystore.orig installKeystore
rpl "%HOSTNAME%" "core1" installKeystore
rpl "%KEYSTORE_PASS%" "xc.1549" installKeystore

./installKeystore

sudo cp /etc/openfire/security/keystore /etc/openfire/security/keystore.orig
sudo cp security/keystore /etc/openfire/security
sudo chown openfire:openfire /etc/openfire/security/keystore.orig
rm installKeystore
