#!/bin/sh

echo INFO: Setup OpenDJ
sudo /opt/opendj/setup --cli --no-prompt --doNotStart -Z 636 -q --generateSelfSignedCertificate -N XCHANGECORE --adminConnectorPort 4444 -D "cn=Directory Manager" -w xc.1549 -b dc=xchangecore,dc=us -a

echo INFO: Starting OpenDJ
sudo /opt/opendj/bin/start-ds

echo INFO: Creating Admin and User Groups
cp conf/setup.ldif.orig conf/setup.ldif

echo INFO: Replace all the replacements
rpl "%ADMINUSER%" admin conf/setup.ldif
rpl "%ADMINPASS%" xc.1549 conf/setup.ldif
rpl "%COREUSER%" xchangecore conf/setup.ldif
rpl "%COREPASS%" xc.1549 conf/setup.ldif

echo INFO: modify the ldap using setup.ldif
sudo /opt/opendj/bin/ldapmodify -p 636 -D "cn=Directory Manager" -w xc.1549 -X -Z --noPropertiesFile -a -f conf/setup.ldif

echo INFO: removed the setup.ldif
rm conf/setup.ldif
